
###########################################################
# GENERATED FILE. DO NOT EDIT
# Generated by stackato-ops/dev-tools/gemlocker/gemlocker
###########################################################

source (ENV['RUBYGEMS_MIRROR'] or 'https://rubygems.org')

ruby '1.9.3' # prevents hard-to-diagnose errors with bundle install

gem 'vcap_common'       , '1.0.12'
gem 'addressable'       , '2.3.3'
gem 'beefcake'          , '0.3.7'
gem 'cookiejar'         , '0.3.0'
gem 'daemons'           , '1.1.9'
gem 'diff-lcs'          , '1.2.1'
gem 'docopt'            , '0.5.0'
gem 'em-http-request'   , '1.0.3'
gem 'em-socksify'       , '0.2.1'
gem 'eventmachine'      , '1.0.1'
gem 'eventmachine-tail' , '0.6.4'
gem 'fraggle'           , '4.0.1'
gem 'fraggle-block'     , '0.2.0'
gem 'http_parser.rb'    , '0.5.3'
gem 'ipaddress'         , '0.8.0'
gem 'json_pure'         , '1.7.7'
gem 'mustache'          , '0.99.4'
gem 'nats'              , '0.4.26'
gem 'pg'                , '0.14.1'
gem 'posix-spawn'       , '0.3.6'
gem 'rack'              , '1.5.2'
gem 'rake'              , '0.9.6'
gem 'rspec'             , '2.13.0'
gem 'rspec-core'        , '2.13.0'
gem 'rspec-expectations', '2.13.0'
gem 'rspec-mocks'       , '2.13.0'
gem 'ruby-termios'      , '0.9.6'
gem 'sqlite3'           , '1.3.7'
gem 'stackato-kato'     , '2.8.1'
gem 'term-ansicolor'    , '1.0.7'
gem 'thin'              , '1.5.0'
gem 'vic'               , '1.0.0'
gem 'xmlparser'         , '0.7.2.1'
gem 'yajl-ruby'         , '1.1.0'

